# Generated by Django 3.0.4 on 2020-05-08 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=250)),
                ('property_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('booking_amount', models.FloatField(blank=True, null=True)),
                ('property_images', models.ImageField(upload_to='products/%y/%m/%d')),
                ('image1', models.FileField(blank=True, null=True, upload_to='products/%y/%m/%d')),
                ('image2', models.FileField(blank=True, null=True, upload_to='products/%y/%m/%d')),
                ('image3', models.FileField(blank=True, null=True, upload_to='products/%y/%m/%d')),
                ('city', models.CharField(max_length=250)),
                ('property_status', models.CharField(blank=True, max_length=250, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('no_of_bathroom', models.IntegerField()),
                ('no_of_bedroom', models.IntegerField()),
                ('is_air_conditioning', models.BooleanField(blank=True, default=False, null=True)),
                ('is_gym', models.BooleanField(blank=True, default=False, null=True)),
                ('is_laundry_room', models.BooleanField(blank=True, default=False, null=True)),
                ('is_tv_cable', models.BooleanField(blank=True, default=False, null=True)),
                ('is_wifi', models.BooleanField(blank=True, default=False, null=True)),
                ('is_parking', models.BooleanField(blank=True, default=False, null=True)),
                ('is_swimming_pool', models.BooleanField(blank=True, default=False, null=True)),
                ('Balconies', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('property_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
