# Generated by Django 3.0.6 on 2020-06-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_add_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
