# Generated by Django 3.0.6 on 2020-06-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_practise'),
    ]

    operations = [
        migrations.AddField(
            model_name='practise',
            name='is_registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='practise',
            name='Address',
            field=models.TextField(),
        ),
    ]
